apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  namespace: staging
  name: dev-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: staging
  name: dev-rolebinding
subjects:
- kind: Group 
  name: "5b44619d-683a-40c6-9868-758e73bbb61a"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
