apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: remote-cluster-metrics
  namespace: monitoring
  labels:
    release: prometheus-remote
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
  - port: http
    interval: 30s
