apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydjango
spec:
  selector:
    matchLabels:
      app: mydjango
  template:
    metadata:
      labels:
        app: mydjango
    spec:
      containers:
      - name: mydjango
        image: abdulp07/djangomicro
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

--- 
apiVersion: v1
kind: Service
metadata:
  name: mydjango
spec:
  selector:
    app: mydjango
  ports:
  - port: 8000
    targetPort: 8000

